language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer # Updates JDK 8 to the latest available.

before_script:
  - ./gradlew clean generateTests
  - if [ ! -z "$(git status --porcelain)" ]; then git diff; echo -e "\nTest files changed. Did you run ./gradlew generateTests?"; exit 1; fi

script:
  - ./gradlew clean build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "L42l/XejqiN3fAF3oyevzgnGGUWz1AjqoNn0FZjpTWkGYxH8hlCz04AbnXIT1gbo3BVZ6bpftcTTY1g3H5qINShNopfYjPpDMXQulKB7ksVbDCepfezuyKNuzKbMdzj6CXvmqAF5EXmROmv1VaMgJPQVY6W3kWFgd3wPzYOJ5WQ="
    - secure: "iazgbbyxodXd819HGWX3s1Pv4W4cfNiN66VtBvFtVa6xkPS/KhkD275SC6mH3Sp6DgLuSaK5XuBHhP15jc/PBov/00qRc48DruB9zF6oW0CrSvB8VpuSrT2Cr0SvyFlXW9mAyCYrP6i0uC3Ygyntfxmk5CyA5Cx+bqwkVikeg7Y="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/
    - $HOME/.gradle/daemon/native/
